- name: Instalando K3S no MASTER
  vars:
    SERVER_MAIN_IP: '10.10.30.100'
  hosts: SERVER_MAIN
  tasks:
    - name: -> MASTER - Instalando o K3S
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server \
        --cluster-init \
        --token clusterk3slocalbuild \
        --write-kubeconfig-mode 644 \
        --tls-san {{ SERVER_MAIN_IP }}
      register: k3s_install
      ignore_errors: no 
    
#    - name: Lendo k3s server token
#      ansible.builtin.slurp:
#        src: /var/lib/rancher/k3s/server/token
#      register: k3s_server_token
#      ignore_errors: no    

#    - name: prepare token to servers 
#      set_fact: 
#        k3s_token: "{{ k3s_server_token['content'] | b64decode | trim }}"
    
    - name: -> MASTER - Acessar o arquivo de configuração do K3S
      shell: cat /etc/rancher/k3s/k3s.yaml
      register: k3s_cfg
      ignore_errors: no 
    
    - name: -> MASTER - Copiar o arquivo de configuração do k3s 
      delegate_to: localhost
      copy:
        content: "{{ k3s_cfg.stdout }}"
        dest: "{{ playbook_dir }}/k3s.cfg.yaml"
      ignore_errors: no
#- name: Instalando K3S no Servidores secundarios
#  hosts: SERVER_SECONDARY
#  vars:
#    SERVER_MAIN_IP: '10.10.30.100'
#  tasks:
#    - name: -> Server Adicional - Instalando o K3S
#      shell: |
#        curl -sfL https://get.k3s.io | sh -s - server \
#        --token "{{ hostvars['k3s1'].k3s_token }}" \
#        --server https://{{ SERVER_MAIN_IP }}:6443
#      register: k3s_install
#      ignore_errors: no 

- name: NODES - Instalando K3s nos NODES
  hosts: NODES
  vars:
    SERVER_MAIN_IP: '10.10.30.100'
  tasks:
    - name: -> NODE - INSTALL K3S 
      shell: |
        curl -sfL https://get.k3s.io | sh -s - agent \
        --server https://{{ SERVER_MAIN_IP }}:6443 \
        --token clusterk3slocalbuild
      register: k3s_install 
      ignore_errors: no
