all:
  vars:
    ansible_user: agent
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
SERVER_MAIN:
  hosts:
    k3s1:
      ansible_host: 10.10.30.100
      ansible_become: yes
NODES:
  hosts:
    k3s-node1:
      ansible_host: 10.10.30.101
      ansible_become: yes
    k3s-node2:
      ansible_host: 10.10.30.102
      ansible_become: yes
    k3s-node3: 
      ansible_host: 10.10.30.103
      ansible_become: yes
    k3s-node4: 
      ansible_host: 10.10.30.104
      ansible_become: yes
RECURSOS:
  children:
    SERVER_MAIN:
    SERVER_SECONDARY:
    NODES:

