- name: Instalar RANCHER - MANAGER
  hosts: MANAGER
  vars:
    MANAGER_IP: 10.10.30.200
  tasks:
    - name: -> MANAGER - Cria diretório de configuração
      file:
        path: /etc/rancher/rke2
        state: directory
      ignore_errors: no
    - name: -> MANAGER - Adiciona configuração
      copy:
        dest: /etc/rancher/rke2/config.yaml
        content: |
          token: managerclusterk3slocalbuilder
          tls-san:
            - {{ MANAGER_IP }}
      ignore_errors: no
    - name: -> MANAGER - Instalar RANCHER
      shell: |
        curl -sfL https://get.rancher.io | sh
      register: rancher_install
      ignore_errors: no

    - name: -> MANAGER - Habilia serviço
      shell: |
        sudo systemctl enable rancherd-server.service && \
        sudo systemctl start rancherd-server.service
      register: rancher_enable
      ignore_errors: no
