apiVersion: v1
kind: Service
metadata:
  name: uptime-svc
  namespace: uptime-kuma
spec:
  selector:
    app: uptime-kuma
  ports:
    - name: http
      port: 3001
      protocol: TCP
      targetPort: 3001
  type: LoadBalancer
  loadBalancerIP: 10.10.30.155
